Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import keyword
>>> keyword.kwlist
['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
>>> import keyword as kw
>>> kw.kwlist
['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
>>> kwlist
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    kwlist
NameError: name 'kwlist' is not defined
>>> from keyword import kwlist
>>> kwlist
['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
>>> from keyword import kwlist, iskeyword
>>> from keyword import *
>>> from keyword import kwlist as kwl
>>> kwl
['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
>>> import tkinter
>>> import pandas
>>> 
=========== RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py ==========
>>> 
=========== RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py ==========

=========== RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py ==========

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/UFT/15novML/day8/script.py", line 15, in <module>
    tkn.Button(app,text='+',width = 2,command=calculate).place(x=20,y=300)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2650, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: can't invoke "button" command: application has been destroyed
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/UFT/15novML/day8/script.py", line 15, in <module>
    tkn.Button(app,text='+',width = 2,command=calculate).place(x=20,y=300)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2650, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: can't invoke "button" command: application has been destroyed
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/UFT/15novML/day8/script.py", line 15, in <module>
    tkn.Button(app,text='+',width = 2,command=calculate).place(x=20,y=300)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2650, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: can't invoke "button" command: application has been destroyed
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/UFT/15novML/day8/script.py", line 15, in <module>
    tkn.Button(app,text='+',width = 10,command=calculate).place(x=20,y=300)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2650, in __init__
    Widget.__init__(self, master, 'button', cnf, kw)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2572, in __init__
    self.tk.call(
_tkinter.TclError: can't invoke "button" command: application has been destroyed
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py

= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
nice
>>> 
= RESTART: C:/Users/hp/Desktop/UFT/15novML/day8/script.py
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/UFT/15novML/day8/script.py", line 29, in <module>
    app.mainloop()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> def abc(n):
	return n*5

>>> abc(10)
50
>>> lambda n:n*5
<function <lambda> at 0x000001E51CFBB1F0>
>>> abc1 = lambda n:n*5
>>> abc1
<function <lambda> at 0x000001E51CFBB310>
>>> abc1(10)
50
>>> 